#!/usr/bin/env python3
"""build_standard.py — assembles spec/*.md into the single combined standard.

Reads every section named NN-*.md in spec/ (00..26), concatenates them in
numeric order into spec/Beluma-Standard-v1.0.md, and renders the HTML via
tools/md2html.py. This makes the internal "Standard" links resolve.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPEC = ROOT / "spec"
OUT_MD = SPEC / "Beluma-Standard-v1.0.md"
OUT_HTML = SPEC / "Beluma-Standard-v1.0.html"

PREAMBLE = """# Beluma Language Standard v1.0

> Official consolidated edition. Assembled from the numbered sections of
> `spec/` by `tools/build_standard.py`. Do not edit this file directly — edit
> the numbered section files.

"""

FOOTER = """

---

*End of the Beluma Language Standard v1.0. Maintained by the Beluma Language
Academy (§25). Report corrections via the repository issue tracker.*
"""


def section_files():
    files = []
    for p in SPEC.glob("[0-9][0-9]-*.md"):
        m = re.match(r"(\d\d)-", p.name)
        if m:
            files.append((int(m.group(1)), p))
    files.sort()
    return [p for _, p in files]


def main():
    files = section_files()
    if not files:
        print("no spec sections found")
        return 1
    parts = [PREAMBLE]
    for p in files:
        body = p.read_text(encoding="utf-8").rstrip()
        parts.append(body)
        parts.append("\n\n---\n\n")
    parts.append(FOOTER)
    OUT_MD.write_text("\n".join(parts), encoding="utf-8")
    print(f"wrote {OUT_MD.relative_to(ROOT)} ({len(files)} sections)")

    sys.path.insert(0, str(ROOT / "tools"))
    import md2html
    md2html.build(OUT_MD)
    print(f"wrote {OUT_HTML.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
